language: php

php:
  - 5.6

services:
  - mysql

script:
  # - composer install

before_script:
  - composer create-project symfony/framework-standard-edition my_project_name "2.*"

notifications:
  email:
    - laurent@llovem.eu